font=Terminus:size=9
shell=/bin/tmux attach
pad=16x16
resize-delay-ms=0

#Alduin
#[colors]
#background=1c1c1c
#foreground=dfdfaf
#regular0=262626
#regular1=af5f5f
#regular2=87875f
#regular3=af875f
#regular4=878787
#regular5=af8787
#regular6=87afaf
#regular7=dfdfaf
#bright0=626262
#bright1=af5f5f
#bright2=87875f
#bright3=af875f
#bright4=878787
#bright5=af8787
#bright6=87afaf
#bright7=dfdfaf
#alpha=1


